### ISSUE TITLE
[Enhancement] [Module - ChestFiller] Allow defining global chest location to load content from.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#200]
Similar to classchests, so you can load random chest content into the battlefield that contains custom items like shields with designs, specific potions, special arrows, etc.

**Comment by slipcor** [comment]
v1.3.2.133 - [ChestFiller] add github issue #200, a configurable chest to set items

**Comment by mibby** [comment]
@slipcor Doesn't seem to be working properly. Defined chest inventories do not fill at all from the global chest to read contents from.

```
  chestfiller:
    chestlocation: world:-6279,122,2114
    clear: true
    cfitems: '1'
    cfmaxitems: 5
    cfminitems: 1
```
```
inventories:
- world:-9303,122,2968
- world:-9306,122,2973
- world:-9302,122,2976
- world:-9299,122,2972
```

The chests just remain empty all the time. Tested with both clear: true and clear: false.
