### ISSUE TITLE
[Module - Announcements] Advert breaking after first announcement.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#265]
PVPArena dev 222
Announcements 1.3.3.214

```
  announcements:
    radius: 0
    color: AQUA
    join: false
    start: true
    end: false
    winner: false
    loser: false
    prize: false
    custom: false
    advert: true
```

Announcement advert breaks after the first announcement. 

Arena debug.
http://paste.ubuntu.com/23761928/

General debug.
http://paste.ubuntu.com/23761929/

* Joined spleef.
* Outside player saw advert.
* Left spleef.
* Joined spleef again.
* Outside player did not see advert.
* Left spleef again.

This occurs with every unique arena in a shortcut rotation. Works the first time, doesn't the second forward.

Downgrading to Announcements 1.3.3.194 (version before this last commit https://github.com/slipcor/pvparena_modules/commit/d1ee7824eeeca442a452af996528c67dbd64f183) fixes the problem.
