### ISSUE TITLE
BlockDissolve - not working 

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#284]
BlockDissolve - v1.3.3.223

does nothing ... 😢

**Comment by slipcor** [comment]
1) did you restart the server?
2) did you set "modules.blockdissolve.materials" to the thing you use as your arena floor? What did you seet it to?

**Comment by Oruss7** [comment]
1 - yes
2 - my conf:
```
modules:
  blockdissolve:
    calcoffset: 0.333
    materials: '159:1'
    startseconds: 5
    ticks: 8
```

or full conf:
http://pastebin.com/tw3iXeBd
