### ISSUE TITLE
Error on removing arena related to LateLounge

### ISSUE THREAD

**Issue by SXRWahrheit** [slipcor/pvparena#333]
```
[15:37:17] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [-5114 244 4650] => "/pa remove Canyon"
[15:37:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.4.291
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-93e20b3-31d3159]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.latelounge.LateLounge.hasSpawn(LateLounge.java:141) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:346) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-93e20b3-31d3159]
	... 15 more
```

```yaml
configversion: 1.3.3.217
chat:
  colorNick: true
  defaultTeam: false
  enabled: true
  onlyPrivate: false
  toGlobal: none
cmds:
  defaultjoin: true
  whitelist:
  - ungod
damage:
  armor: true
  bloodParticles: true
  fromOutsiders: false
  spawncamp: 1
  weapons: false
general:
  classspawn: false
  classSwitchAfterRespawn: false
  customReturnsGear: false
  enabled: true
  gm: 0
  leavedeath: false
  lang: none
  owner: server
  regionclearexceptions: []
  quickspawn: false
  prefix: Arena
  showRemainingLives: true
  smartspawn: false
  time: 6000
  type: none
  wand: PAPER
goal:
  livesPerPlayer: false
  endCountDown: 0
  playerlives:
    plives: 5
  blockdestroy:
    blocktype: IRON_BLOCK
    bdlives: 1
  dom:
    spamoffset: 3
    claimrange: 3
    dlives: 10
    onlywhenmore: false
  flags:
    flagType: WOOL
    flives: 3
    mustBeSafe: true
    woolFlagHead: true
    effect: none
  food:
    fmaxitems: 50
    fplayeritems: 10
    fteamitems: 100
  infected:
    iilives: 1
    inlives: 1
  liberation:
    llives: 3
  playerdm:
    pdlives: 3
  tank:
    tlives: 1
  teamdc:
    tdclives: 10
    tdcitem: WOOL
  teamdm:
    tdlives: 10
  teamlives:
    tlives: 10
  time:
    timedend: 0
    winner: none
  pillars:
    announcetick: true
    pillives: 10
    onlyfree: true
    breakable: true
    tickpoints: 1
    tickinterval: 20
    announceoffset: 3
    maxclicks: 10
    maxheight: 5
    emptyheight: 1
    teamheight: 2
    claimall: false
items:
  excludeFromDrops: none
  keepOnRespawn: none
  minplayers: 2
  random: true
  rewards: none
  takeOutOfGame: none
join:
  range: 0
  forceregionjoin: false
  onlyifhasplayed: false
block:
  blacklist: []
  whitelist: []
goals:
- PlayerLives
mods:
- Announcements
- ArenaBoards
- BattlefieldJoin
- StandardSpectate
- Vault
- LateLounge
- StandardLounge
msg:
  lounge: Welcome to the arena lounge! Hit a class sign and then the lapis block to
    flag yourself as ready!
  playerjoined: '%1% joined the Forest Arena!'
  playerjoinedteam: '%1% joined team %2%!'
  starting: The match is starting in the Forest arena! Type &e/pa %1%&r to join!
  youjoined: You have joined the Forest Arena!
  youjoinedteam: You have joined team %1%!
perms:
  alwaysJoinInBattle: false
  explicitArenaNeeded: false
  explicitClassNeeded: false
  fly: false
  loungeinteract: false
  joinInBattle: false
  joinWithScoreboard: true
  teamkill: false
  specTalk: true
  spectatorinteract: false
  default:
  - -mcmmo.ability.*
  - -mcmmo.skills.*
player:
  autoIgniteTNT: true
  clearInventory: NONE
  collision: true
  dropsEXP: false
  dropsInventory: false
  exhaustion: 0.0
  hungerforkill: 0
  foodLevel: 20
  health: 20
  healforkill: false
  hunger: true
  itemsonkill: none
  mayChangeArmor: true
  maxhealth: -1
  preventDeath: true
  refillCustomInventory: true
  refillInventory: true
  refillforkill: false
  removearrows: false
  saturation: 20
  quickloot: false
  flyspeed: -10.0
  walkspeed: -10.0
protection:
  enabled: true
  punish: false
  spawn: 0
ready:
  autoClass: Gladiator
  block: LAPIS_BLOCK
  checkEachPlayer: false
  checkEachTeam: true
  enforceCountdown: false
  minPlayers: 2
  maxPlayers: 12
  maxTeam: 2
  neededRatio: 0.5
time:
  startCountDown: 20
  regionTimer: 10
  teleportProtect: 5
  resetDelay: -1
  warmupCountDown: 5
  pvp: 0
tp:
  death: spectator
  exit: old
  lose: old
  win: old
  offsets: []
uses:
  classSignsDisplay: false
  deathMessages: true
  deathMessagesCustom: true
  evenTeams: true
  ingameClassSwitch: false
  invisibilityfix: false
  evilinvisibilityfix: false
  overlapCheck: true
  playerclasses: false
  scoreboard: false
  scoreboardrounddisplay: false
  suicidepunish: false
  teamrewards: false
  teleportonkill: false
  woolHead: true
modules:
  announcements:
    radius: 0
    color: AQUA
    join: true
    start: true
    end: false
    winner: true
    loser: false
    prize: false
    custom: false
    advert: false
  vault:
    betpot: true
    bettime: 60
    betWinFactor: 1.0
    betWinTeamFactor: 1.0
    betWinPlayerFactor: 1.0
    entryfee: 5
    killreward: 6.0
    minplaytime: 0
    vminplayers: 2
    minbet: 0.0
    maxbet: 25.0
    winFactor: 2.0
    winreward: 5
    winrewardPlayerFactor: 1.0
    reward:
      playerDeath: 0.0
      playerKill: 0.0
      playerScore: 0.0
      trigger: 0.0
      playerWin: 0.0
    winPot: true
    permfactors:
    - pa.vault.vip:2.0
    - pa.vault.supervip:3.0
  aftermatch:
    aftermatch: 'off'
  arenamaps:
    aligntoplayer: false
    showspawns: true
    showplayers: true
    showlives: true
  arenavote:
    everyone: true
    autostart: false
    readyup: 30
    onlySpamToJOIN: false
    seconds: 30
    world: none
  battlefieldguard:
    enterdeath: false
  betterfight:
    usemessages: false
    onehititems: none
    resetkillstreakondeath: true
    explodeondeath: true
  bettergears:
    head: true
    chest: true
    leg: true
    foot: true
    onlyifleather: false
  blockrestore:
    hard: false
    offset: 1
    restoreblocks: true
    restorechests: false
  colorteams:
    hidename: false
    colornick: true
  fixinventoryloss:
    gamemode: true
    inventory: true
  items:
    interval: 0
    items: none
    respawnseconds: 10
  respawnrelay:
    respawnseconds: 10
    choosespawn: false
  playerfinder:
    maxradius: 100
  powerups:
    dropspawn: false
    usage: 'off'
  skins:
    vanilla: false
  specialjoin:
    showplayers: true
  startfreeze:
    freezetimer: 0
  turrets:
    maxdegrees: 90.0
    mininterval: 0
  walls:
    wallmaterial: SAND
    wallseconds: 300
  worldedit:
    autoload: false
    autosave: false
time_intervals:
  '1': 1..
  '2': 2..
  '3': 3..
  '4': 4..
  '5': 5..
  '10': 10 %s
  '20': 20 %s
  '30': 30 %s
  '60': 60 %s
  '120': 2 %m
  '180': 3 %m
  '240': 4 %m
  '300': 5 %m
  '600': 10 %m
  '1200': 20 %m
  '1800': 30 %m
  '2400': 40 %m
  '3000': 50 %m
  '3600': 60 %m
flagColors:
  red: WHITE
  blue: BLACK
classitems:
  Gladiator: DIAMOND_SWORD,BOW,ARROW:48,IRON_HELMET,IRON_CHESTPLATE,IRON_LEGGINGS,IRON_BOOTS
teams:
  red: RED
  blue: BLUE
spawns:
  redlounge: infinitus,-161,149,6,88.60086059570312,9.30000114440918
  bluelounge: infinitus,-246,149,6,-88.54926300048828,12.449973106384277
  spectator: infinitus,-203,148,-9,-0.9492974281311035,22.04999351501465
  bluespawn2: infinitus,-245,134,-12,-44.74713134765625,10.500288009643555
  redspawn2: infinitus,-162,134,23,-220.5465087890625,8.100441932678223
  redspawn1: infinitus,-155,141,-3,-269.59686279296875,8.100447654724121
  bluespawn1: infinitus,-252,141,14,-90.9488525390625,16.800447463989258
  bluespawn3: infinitus,-225,140,-1,-43.698486328125,13.650457382202148
  redspawn3: infinitus,-181,140,12,-224.14837646484375,8.85045337677002
  redspawn4: infinitus,-185,134,-13,-328.5474853515625,12.600382804870605
  bluespawn4: infinitus,-218,133,24,-142.84808349609375,12.150371551513672
  bluespawn5: infinitus,-230,133,0,-65.446533203125,7.050386905670166
  redspawn5: infinitus,-178,133,12,-232.54522705078125,10.050336837768555
arenaregion:
  battle: infinitus,-254,126,-20,-153,146,31,cuboid,0,4095,BATTLE
  watch: infinitus,-254,147,-20,-153,152,31,cuboid,0,0,WATCH
```
