### ISSUE TITLE
Disable classes?

### ISSUE THREAD

**Issue by WeasomeKarma** [slipcor/pvparena#340]
Hello, 

Is it possible to disable the need of classes entirely? Just let players bring what they own in?

Thanks!

**Comment by Oruss7** [comment]
Hi, 

Yes, and not. To achieve that, i made only 1 class and set it default:
```
ready:
  autoClass: set_de_pvp
...
classitems:
  set_de_pvp: IRON_BOOTS,IRON_LEGGINGS,...
```
