### ISSUE TITLE
Class creation fills entries with 'null'.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#350]
Paper dev 398 (Spigot 1.13.2)
PVPArena 1.13 - Compiled as of https://github.com/slipcor/pvparena/commit/43f8dce3d3b000db18fb5bbe6d51f61a0bc56a34

When creating a class with ```/pa <arena> class save <name>``` with an empty inventory, it fills the class config with null entries. Wouldn't it be better to assume if it doesn't exist, fill the spot with air or presume null?

Likewise, if the ```armor:``` section is missing from the class in the config, the class fails to load when the arena config loads.  Instead, if a class section is missing, presume null/air as a fallback?

```
    spleef:
        items:
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        - null
        offhand:
        -   ==: org.bukkit.inventory.ItemStack
            v: 1631
            type: AIR
            amount: 0
        armor:
        - null
        - null
        - null
        - null
```

*OP note: Untested but I assume even if using a class chest location, you will also need to have item/offhand/armor configured null / existing so the class load doesn't fail.*
