### ISSUE TITLE
CTF flag color logic is broken.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#351]
**Issue**: CTF flag colors are wrong.
https://i.imgur.com/V6hxUoA.jpg

Prior logic was each base's flag was the wool color of the team. I.e. red wool at red base's flag, blue wool at blue base's flag. When you grabbed the flag, the wool turned white.

New logic: Wool flag is only displayed as white. When you grab it, it turns into bedrock.

This wouldn't be bad logic if the flag locations were generic and up for anyone to grab, but because it is a team's specific flag to capture/defend, it is confusing players.

i.e.

```
teams:
  Red: RED
  Blue: LIGHT_BLUE
spawns:
  Redflag: void,416,39,-123
  Blueflag: void,243,39,-100
```

Instead of just being flag1, flag2, flag3, etc.
