### ISSUE TITLE
Config malformatted (create from last build)

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#357]
Hello,

I created a new Arena with dev build you gave to me. I got strange config file:  https://pastebin.com/yHsU4Wcj

```
    armor:
    - ==: org.bukkit.inventory.ItemStack
      v: 1631
      type: LEATHER_HELMET
```
Thanks,

Oruss7
