### ISSUE TITLE
[Enhancement] - Class change in-game via signs.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#83]
@slipcor Would it be possible to be able to change classes in-game via signs like you can do in the lounges? It doesn't currently seem to function when you are in-game, in the battlefield. You need to use the command to change class. I'd like to have class signs near the team spawns, allowing them to right click the sign to change classes on next respawn. So when they die, they can use a new class. More convenient to be able to use signs instead of commands. 

Config settings.
```
general:
  classspawn: false
  classSwitchAfterRespawn: true
  customReturnsGear: false
  enabled: true
  gm: 0
  leavedeath: false
  lang: none
  owner: server
  quickspawn: true
  prefix: CTF
  showRemainingLives: true
  smartspawn: false
  time: -1
  type: none
  wand: 280
uses:
  classSignsDisplay: true
  deathMessages: true
  evenTeams: true
  ingameClassSwitch: true
  invisibilityfix: false
  evilinvisibilityfix: false
  playerclasses: false
  overlapCheck: true
  teamrewards: false
  woolHead: false
```
