### ISSUE TITLE
[Bug] - Duel module does not output requested language line.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#97]
@slipcor 
```
    duel:
      accepted: '%1% &eaccepted the challenge! The game is starting.'
      announce: '%1% &echallenged you! Accept the duel with &r/pa 1v1 accept.'
      requested: You &echallenged &r%1%&e!
      starting: The duel begins!
```

The 'requested' duel line is not outputted to the player requesting the duel. No feedback is given.

PVPArena 1.3.0.550
Duel module 1.3.0.515

Also, perhaps you should add an automatic cancel if the duel is not accepted in 60 seconds so it isn't pending forever?

Edit: It seems the requested line is being sent to the requested player instead of person requesting to duel..
