### ISSUE TITLE
[Bug] - Entry fee is not being added to the winPot.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#98]
```
  vault:
    betpot: false
    bettime: 60
    betWinFactor: 1.0
    betWinTeamFactor: 1.0
    betWinPlayerFactor: 1.0
    entryfee: 25
    killreward: 0.0
    minplaytime: 60
    vminplayers: 2
    minbet: 0.0
    maxbet: 0.0
    winFactor: 1.0
    winreward: 0
    winrewardPlayerFactor: 1.0
    reward:
      playerDeath: 0.0
      playerKill: 0.0
      playerScore: 0.0
      trigger: 0.0
      playerWin: 0.0
    winPot: true
    permfactors:
      pa:
        vault:
          none: 1.0
```

PVPArena 1.3.0.550
Duel module 1.3.0.515
Vault module 1.3.0.525

Get a game started with /pa 1v1 duel <player>. He accepts. We are both charged $25. I leave the arena, he does not win $50 (the total entrance fee from all players). He is also not paid when he kills me 3 times to win the game instead of me leaving with /pa leave.
